# flo Cargo configuration
#
# WASM test runner: requires `cargo (b)install wasm-bindgen-cli`
# Run with:  cargo test --workspace --target wasm32-unknown-unknown

[target.wasm32-unknown-unknown]
runner = "wasm-bindgen-test-runner"